### PR TITLE
Database

### PR DESCRIPTION
**Pull request by ErikssonF**

### CODE REVIEW

**Comment by helenahalldiniths** [comment]
[Setup Database](https://trello.com/c/Xp0dWFiN/52-setup-database)

**Comment by helenahalldiniths** [comment]
[Add database table English - Svenska (Basic version)](https://trello.com/c/sPDMw5Tj/100-add-database-table-english-svenska-basic-version)

**Comment by helenahalldiniths** [comment]
Instructions:
- run npm install (if first time you cloned the repo), else run npm install sqlite3.
- run node app.js

- in your CLI, go to the map where the fruit.db file has been created and enter "sqlite3 fruit.db". (If this doesen't work you might have to install sqlite3)
- your should now be able to write sqlite code. Tyr "Select * from fruit", this should show you everything in the database.

**Review by FelixJacobsen — COMMENTED** [review]
It doesn't seems to work with sqlite. 
This is the error we both are getting.
image

**Review by Philippevial — APPROVED** [review]
We finally got it to work! 
I had to add a environment variable with the path to the sqlite3 folder.

Nicely done!

**Pull request merged**
